### ISSUE TITLE
Feature request: Remove empty defs tag

### ISSUE THREAD

**Issue by jamieburchell** [svg/svgo#1258] opened 2020-06-02 14:07 UTC
Remove `<defs/>` tag

(Apologies if this is already a thing, but I was left with this tag after running an SVG through SVGOMG).

**Comment by ChrisRu** [comment] 2020-08-18 18:53
Duplicate of #1186 , unmerged fix exists.

**Comment by TrySound** [comment] 2021-02-20 16:26
Fixed in https://github.com/svg/svgo/releases/tag/v2.0.3

**Closed by TrySound** 2021-02-20 16:26 UTC
Labels: solved in master
