### ISSUE TITLE
SVGO creates roundingerror (60.882000000000005)

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#1051] opened 2018-10-13 06:40 UTC
Running `svgo 1.1.1` with `--disable=convertPathData` for [File:Comparison_of_Nissen_and_Quonset_huts_(de).svg](https://commons.wikimedia.org/wiki/File:Comparison_of_Nissen_and_Quonset_huts_(de).svg) creates roundingerrors, might be similar to https://github.com/RazrFalcon/svgcleaner/issues/172

svgo -i [input.svg.txt](https://github.com/svg/svgo/files/2475161/input.svg.txt) -o [output.svg.txt](https://github.com/svg/svgo/files/2475162/output.svg.txt)  --pretty --indent=1 --disable=convertPathData -p 3

# Input
[input.svg.txt](https://github.com/svg/svgo/files/2475161/input.svg.txt)
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="65mm" height="45mm" viewBox="0 0 65 45">
 <g font-family="DejaVu Sans" font-size="3.175px" transform="translate(-10.893 -2.54)">
  <rect x="26.614" y="29.232" width="34.268" height="8.1757"/>
 </g>
</svg>
```

# Output
[output.svg.txt](https://github.com/svg/svgo/files/2475162/output.svg.txt)
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="65mm" height="45mm" viewBox="0 0 65 45">
 <path d="M26.614 29.232H60.882000000000005V37.408H26.614z" transform="translate(-10.893 -2.54)" font-family="DejaVu Sans" font-size="3.175"/>
</svg>
```

**Comment by GreLI** [comment] 2018-10-14 16:01
Seems like `convertShapeToPath` doesn't do rounding. Probably, it should.

**Comment by XhmikosR** [comment] 2021-02-20 12:00
@TrySound this may be fixed in master?

**Comment by TrySound** [comment] 2021-02-20 14:02
Still happens with disabled convertPathData

**Comment by TrySound** [comment] 2021-03-06 12:04
Fixed in v2.2.1

**Closed by TrySound** 2021-03-06 12:04 UTC
Labels: bug, solved in master

**Comment by JoKalliauer** [comment] 2021-03-07 08:07
```bash
npm i -g npm
npm i svgo
wget https://github.com/svg/svgo/files/2475161/input.svg.txt
svgo -i input.svg.txt -o output.svg --pretty --indent=1 -p 3
```
with 
[svgo.config.js](https://github.com/svg/svgo/files/6096792/svgo.config.js.txt)


results in 
```xml
<svg xmlns="http://www.w3.org/2000/svg" width="65mm" height="45mm" viewBox="0 0 65 45">
 <path d="M26.614 29.232H60.882000000000005V37.408H26.614z" font-family="DejaVu Sans" font-size="3.175" transform="translate(-10.893 -2.54)"/>
</svg>
```

**Comment by TrySound** [comment] 2021-03-07 08:16
Cannot reproduce with `-p 3`

**Comment by JoKalliauer** [comment] 2021-03-07 08:16
Sorry I somehow had svgo v2.2.0 instead of 2.2.1.
Running `npm -g install svgo` instead of `npm i svgo` fixed the issue.
