### ISSUE TITLE
Size increasement

### ISSUE THREAD

**Issue by Mister-Hope** [svg/svgo#1920] opened 2024-01-02 06:52 UTC
After upgrading to 3.2.0, a lot of my icons are getting increasement after optimizing:

![image](https://github.com/svg/svgo/assets/33315834/07cf4599-bc9d-4e49-ac96-837a8e504083)

![image](https://github.com/svg/svgo/assets/33315834/a9c0ba65-7242-4e81-93b1-169f8c875cd7)

Is it a bug or svgo choose to do so, how should I do to call svgo from command line targeting the minimal size? (Standard is not my primary target, but size is because my project has size limitations)

**Comment by SethFalco** [comment] 2024-01-02 09:30
Hey! That would be unintentional.

Could you please share the SVG with us and I'll take a look?
It's likely one of the new optimizations can just lead to size increases under certain conditions, and we didn't realize that.

**Comment by Mister-Hope** [comment] 2024-01-02 12:40
sorry for not following the template, I upgrade from 3.1.0 I think, but I am not srre. I always install it globally and use it as a bin in command lkne, never create any config files in history.

So I am only 90% sure I previously on 3.1.0.

SO is there any way for me to revert the previous behavior though command line?

**Comment by SethFalco** [comment] 2024-01-02 14:12
> never create any config files ever.

That's interesting, it does look as if it could find a config before.

If you're on macOS or Linux, you probably have a command called `find`. Could you try the following and see if it has results?

```sh
find / -name "svgo.config.*" 2> /dev/null
```

> So I am only 90% sure I previously on 3.1.0.

If you uploaded your SVG I can say with more certainty, but from what I see right now, SVGO v3.1.0 with the default settings was supposed to include those spaces to begin with. (Though we could try to infer this setting based on usage, or only apply the change if the string became shorter, which is a separate issue.)

> SO is there any way for me to revert the previous behavior though command line?

You can create an SVGO config file in the same directory you're trying to execute it in, or anywhere else if you point to in with the `--config` argument. It should contain the following content:

**`svgo.config.js`**
```js
module.exports = {
  plugins: [
    {
      name: "preset-default",
      params: {
        overrides: {
          convertPathData: {
            noSpaceAfterFlags: true
          }
        }
      }
    }
  ]
}
```

---

To reiterate, please either provide the SVG or a minimal example that produces the same issue, then I can take a deeper look. I will not debug from a screenshot.

**Comment by Mister-Hope** [comment] 2024-01-02 14:44
Here are my svg files, currently I am away from my computer and I am communicating with my phone, I will check if I have any config files later and give an update here, thanks again for your help.

**Comment by Mister-Hope** [comment] 2024-01-02 14:44
https://github.com/inNENU/resource/tree/main/data/icon

**Comment by SethFalco** [comment] 2024-01-02 15:03
I've tested with this:

https://github.com/inNENU/resource/blob/c31036b5d250d8b471f60df7ee5b8f491ae3471e/data/icon/weather/night/03.svg?short_path=cc66228

SVGO v3.1.0 and SVGO v3.2.0 produce the same result in both scenarios:

* Default config (which makes the file larger)
* The proposed config in my comment above (that makes the file smaller)

---

I'll give you some time to figure things out once you're on your PC. Please come back to this ticket once you have an understanding of your environment before and after, and you can reproduce the issue. It's better to give more information later, than incomplete information sooner.

For example, try to go back to version v3.1.0 and see the result, etc.

Later, I'll review if we should add some logic to skip updating the path if we've made it larger, or potentially see if there's any consequence to enabling `noSpaceAfterFlags` by default.

**Comment by XhmikosR** [comment] 2024-01-03 05:39
I actually noticed this too in https://github.com/twbs/icons, especially for the svg sprite icon. I haven't set up a size action because the icons are thousands but the zip file increased after 3.2.0 but 0.1 MB.

The dist file changes are as separate commits in this branch https://github.com/twbs/icons/pull/1897/commits and the config is [here](https://github.com/twbs/icons/blob/main/svgo.config.mjs).

**Comment by Mister-Hope** [comment] 2024-01-03 12:48
@SethFalco I still have other problems in my case, I confirm that I have no svgo config files in my project folder or any parent folder.

Is there any places else where svgo could read when running on windows from command line?

**Comment by Mister-Hope** [comment] 2024-01-03 12:51
The other issue is that when I was trying to rerun on my pc using `svgo -f ./` for the minified svgo files. some of the files changed:

After:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><path fill="#FF5656" d="M913.082 285.624A220.765 220.765 0 0 0 735.73 108.27a1243 1243 0 0 0-219.494-20.489h-10.217a1243 1243 0 0 0-219.547 20.542 220.765 220.765 0 0 0-177.353 177.352 1243 1243 0 0 0-20.647 221.03v7.2q.317 110.541 20.647 221.082a220.765 220.765 0 0 0 177.3 177.353c74.858 13.712 149.77 20.594 224.63 20.594a1244 1244 0 0 0 224.681-20.647 220.765 220.765 0 0 0 177.353-177.353c13.765-74.859 20.594-149.717 20.594-224.63 0-74.91-6.882-149.77-20.647-224.681z"/><path fill="#FFF" d="M756.376 257.141c0-16.094-15.352-12.07-20.117-7.306-9.212 9.9-33.406 30.07-85.13 40.712a105.3 105.3 0 0 1-23.823 2.541c-24.935 0-45.847-8.047-69.724-17.576-27.53-10.641-58.658-22.765-101.223-22.765-3.653 0-7.306 0-10.959.37-46.218 2.224-86.188 22.395-115.2 37.43-8.47 4.235-17.047 8.418-25.676 12.441l-2.542-6.194-.37-.37a18.74 18.74 0 0 0-24.565-9.9 18.2 18.2 0 0 0-9.9 10.27 19.27 19.27 0 0 0 0 14.294L458.212 763.63c2.912 6.989 9.53 11.383 17.259 11.383a18.74 18.74 0 0 0 17.258-26.047l-65.382-154.747a105.35 105.35 0 0 1 63.106-47.33c11.33-2.912 23.082-4.764 35.947-4.764 24.565 0 48.388 5.505 73.694 11.382 23.082 5.135 46.588 10.588 69.67 10.588 34.836 0 61.624-12.07 84.707-37.747a18.5 18.5 0 0 0 1.853-5.823V257.088z"/></svg>
```

Before: 

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><path fill="#FF5656" d="M913.082 285.624A220.765 220.765 0 0 0 735.73 108.27a1243 1243 0 0 0-219.494-20.489h-10.217a1243 1243 0 0 0-219.547 20.542 220.765 220.765 0 0 0-177.353 177.352 1243 1243 0 0 0-20.647 221.03v7.2q.317 110.541 20.647 221.082a220.765 220.765 0 0 0 177.3 177.353c74.858 13.712 149.77 20.594 224.63 20.594a1244 1244 0 0 0 224.681-20.647 220.765 220.765 0 0 0 177.353-177.353c13.765-74.859 20.594-149.717 20.594-224.63 0-74.91-6.882-149.77-20.647-224.681z"/><path fill="#FFF" d="M756.376 257.141c0-16.094-15.352-12.07-20.117-7.306-9.212 9.9-33.406 30.07-85.13 40.712a105.3 105.3 0 0 1-23.823 2.541c-24.935 0-45.847-8.047-69.724-17.576-27.53-10.641-58.658-22.765-101.223-22.765-3.653 0-7.306 0-10.959.37-46.218 2.224-86.188 22.395-115.2 37.43-8.47 4.235-17.047 8.418-25.676 12.441l-2.542-6.194-.37-.37a18.74 18.74 0 0 0-24.565-9.9 18.21 18.21 0 0 0-9.9 10.27 19.27 19.27 0 0 0 0 14.294L458.212 763.63c2.912 6.989 9.53 11.383 17.259 11.383a18.74 18.74 0 0 0 17.258-26.047l-65.382-154.747a105.35 105.35 0 0 1 63.106-47.33c11.33-2.912 23.082-4.764 35.947-4.764 24.565 0 48.388 5.505 73.694 11.382 23.082 5.135 46.588 10.588 69.67 10.588 34.836 0 61.624-12.07 84.707-37.747a18.5 18.5 0 0 0 1.853-5.823V257.088z"/></svg>
```

![image](https://github.com/svg/svgo/assets/33315834/afd62773-7500-4a0c-931f-5479f421d3be)

Any ideas how this happends?

**Comment by SethFalco** [comment] 2024-01-03 12:57
@Mister-Hope

> Is there any places else where svgo could read when running on windows from command line?

Technically, that makes sense now. SVGO is acting as if it can't find a SVGO config file _now_. But to get the results you had before, it should've required an SVGO config file to specify those additional optimizations.

Let's not worry about that. For now, could you to please define an SVGO config file and work with that, and in a future version we'll refrain from updating the path if it becomes longer?

You can specify the config that I gave you in a previous message.

> Any ideas how this happends?

That's just one of the new optimizations that was introduced in SVGO v3.2.0. Looks to me that it's probably https://github.com/svg/svgo/pull/1873, which reduces the precision of the radius of circular arcs if is has a negligible impact on the sagitta. That's intentional and should yield no difference in rendering.

I've also opened your before and after in a browser and can confirm, there is no change in the vector. It just had more precision that what was needed before.

**Comment by Mister-Hope** [comment] 2024-01-03 13:52
thanks.for.the reply , I am just curious why an optimized.file.can still be optimized again, that should be a bug?

i am not worrying about the optimized result would change.

**Comment by KTibow** [comment] 2024-01-03 14:22
> I am just curious why an optimized file can still be optimized again, that should be a bug?

in general, some optimizations lead to other optimizations, but they don't go in order by default so they can't work.

in the specific case of sagitta optimizations, admittedly if you run it multiple times in some cases it will decrease. that it because it calculates error relative to the original. i *could* modify the code to calculate error relative to the last one, simulating multipass behavior, although that might cause some visible impact.

**Comment by XhmikosR** [comment] 2024-01-03 15:11
> @XhmikosR Could you please confirm if my testing methodology is correct?

Thanks for the reply, I really appreciate it. It seems I misread the results as everything is indeed smaller with 3.2.0.

I checked again and the zip file size is down by 0.2MB and the svg-sprite brotli size is also smaller. gzip might be slightly bigger but the difference is marginal.

**Comment by SethFalco** [comment] 2024-03-01 22:34
I've looked into this, and opted not to take action.

Overall, the issue is resolved by setting the `noSpaceAfterFlags` option to `true`. I don't think it's worth adding a check to only set the path if it's become smaller, as other factors play into it too, namely transforms, and the option already achieves the desired result.

Meanwhile, we won't change the default value of the option or work around is outside the config because of the issue described in:

* https://github.com/svg/svgo/issues/1138

**Closed by SethFalco** 2024-03-01 22:34 UTC
Labels: bug
