### ISSUE TITLE
SVGO removing <missing-glyph> element when <font-face> tag is self closing

### ISSUE THREAD

**Issue by thegoldentoilet** [svg/svgo#226] opened 2014-07-10 16:04 UTC
I am running into a problem in Chrome where when a SVG is technically malformed according to http://validator.w3.org/check by not having the closing font-face tag.  This causes the missing-glyph element to be deleted out of the optimized SVG. This causes the font to not be recognized by the browser.

**Comment by GreLI** [comment] 2015-01-19 15:57
Well, it's not a bug. Self-closing tags are perfectly legal in XML, it's more like a Chrome bug.

**Closed by GreLI** 2015-01-19 15:57 UTC
