### ISSUE TITLE
removeDimensions isn't removing width or height

### ISSUE THREAD

**Issue by scottsandersdev** [svg/svgo#1650] opened 2022-02-10 23:22 UTC
**Describe the bug**
I've setup svgo as a node script to optimize our svg assets as a pre-commit hook, but one of the plugins I tested had no impact on the file. I have a simple config to test things out - 

```
module.exports = {
  plugins: ["removeDimensions"],
};
```

But after running the script, the width and height are still on the svg. Am I missing something?

```
<svg width="104" height="34" viewBox="0 0 104 34" xmlns="http://www.w3.org/2000/svg"><rect width="102" height="32" rx="16" transform="translate(1 1)" fill="#FFF" stroke="#000" fill-rule="evenodd"/></svg>
```

**Desktop (please complete the following information):**
 - SVGO Version 2.8.0
 - NodeJs Version 4.17.6
 - OS: macOS Big Sur

**Comment by metamorfoso** [comment] 2022-02-16 04:44
A workaround I found in the meantime is to _also_ explicitly disable `removeViewBox`:

```javascript
plugins: [
    {
      name: 'removeViewBox',
      active: false,
    },
    'removeDimensions',
  ],
```

I'm not sure if it's a bug or an undocumented requirement (I didn't see it in the docs or release notes, but it's possible I missed it).

Anyway, the workaround seems to be giving the kind of output I'd expect for `removeDimensions`. That is if the presence of a viewbox property is acceptable in your case. It seems there has to be either a viewbox or width & height -- I don't know enough about SVGs to say whether this makes sense.

I got the idea from the docs for `svgr`, which has `svgo` as a dependency:
https://react-svgr.com/docs/migrate/#svgo

> ...you have to remove viewBox by yourself if you use a custom SVGO config with --icon or --no-dimensions option.

**Comment by AlpayY** [comment] 2022-02-23 14:24
@metamorfoso 
> A workaround I found in the meantime is to also explicitly disable removeViewBox

This is already mentioned in the [description of the plugin](https://github.com/svg/svgo/blob/d2785ae70750fb6e344254bebe3c2e163db0a0e1/README.md#built-in-plugins), so not a bug and already documented.

**Comment by wqjiao** [comment] 2022-09-14 03:37
@scottsandersdev Have you solved your problem？I had the same problem

**Comment by TrySound** [comment] 2022-11-16 12:06
Please post an example

**Comment by TrySound** [comment] 2022-11-16 13:05
Im away from computer next few days. Checked only with svgomg and all worked. The only thing I see could go wrong is config not loaded by svg. How do you run it?

**Comment by vgtmhl** [comment] 2022-11-16 14:02
I am using it via `svgr` CLI, to create TSX components out of svg files: 
`svgr -d src/components/icons_new --template src/icons/template.js --icon --typescript src/icons_new`


I believe the configs are loaded because if I change some configs in `svgo.config.js`, then the output does change (e.g. if I remove `preset-default`, then no optimization is done on the SVG content. But in the destination svg above, where the `preset-default` is enabled, the svg is indeed optimized)

---

`template.js` from the CLI command is:

```
function template({ componentName, jsx, props }, { tpl }) {
  return tpl`
    import { SVGProps } from 'react'
    import { ExtraSvgProps } from 'interfaces/Icon'
    const ${componentName} = (props: SVGProps<SVGSVGElement> & ExtraSvgProps) => ${jsx}
    export default ${componentName}
`
}

module.exports = template
```

**Comment by TrySound** [comment] 2022-11-16 15:22
Alright, there is a chance svgr customize your svg with this --icon flag. Could you pls check with svgo cli.

**Comment by TrySound** [comment] 2022-11-16 15:23
Btw you can also look at svgo-jsx
https://github.com/svg/svgo-components/tree/main/packages/svgo-jsx

**Comment by vgtmhl** [comment] 2022-11-16 16:11
Actually yes, you are very correct, that is exactly what that `--icon` flag does, from https://www.npmjs.com/package/@svgr/cli:

`--icon   ->   use "1em" as width and height`

Now it works like a charm, thanks you:D

**Comment by SethFalco** [comment] 2023-11-14 00:48
Looks like everything was resolved here, so I'll close the issue.

The initial problem with needing to disable `removeViewbox` is already documented, and the other issue that kept the `1em` dimensions was SVGR.

Feel free to comment or open a new issue if I've missed anything.

**Closed by SethFalco** 2023-11-14 00:48 UTC
Labels: bug
