### ISSUE TITLE
converts comma to space in stroke-dasharray

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#1402] opened 2021-03-03 16:26 UTC
**Describe the bug**
librsvg 2.40 (used on Wikipedia) does not support spaces in "stroke-dasharray"

**To Reproduce**
```bash
npm i svgo
wget https://upload.wikimedia.org/wikipedia/commons/8/8a/EKG-Reto_001_BugSolved.svg
svgo -i EKG-Reto_001_BugSolved.svg -o output.svg
```
Compare input and output with:
https://commons.wikimedia.org/wiki/Commons:Commons_SVG_Checker?withJS=MediaWiki:CommonsSvgChecker.js

**Expected behavior**
If a file uses commas in 'stroke-dasharray' there should be an option to not convert them to spaces, otherwise svgo breaks the rendering of files.
[scour](https://github.com/scour-project/scour) allways keeps the way it was (as svgo 1.x)
[svgcleaner](https://github.com/RazrFalcon/svgcleaner) has an option for [--list-separator comma](https://github.com/RazrFalcon/svgcleaner/blob/master/docs/svgcleaner.adoc#set-number-list-separator)

**Screenshots**
input:
![input](https://user-images.githubusercontent.com/15687581/109836873-e534df80-7c44-11eb-86ff-5447e847e546.png)

output:
![output](https://user-images.githubusercontent.com/15687581/109836863-e2d28580-7c44-11eb-9f49-79c048bab39d.png)

**Desktop (please complete the following information):**
 - SVGO Version 2.2.0
 - npm --version 7.6.0
 - OS: Fedora 32
 
**Additional context**
Example File:
[EKG-Reto_001_BugSolved.svg.txt](https://github.com/svg/svgo/files/6077465/EKG-Reto_001_BugSolved.svg.txt)
source: https://commons.wikimedia.org/wiki/File:EKG-Reto_001_BugSolved.svg

**Comment by TrySound** [comment] 2021-03-03 17:18
So to make it universal dasharray numbers should be converted to string with commas, right?

**Comment by JoKalliauer** [comment] 2021-03-03 17:34
> So to make it universal dasharray numbers should be converted to string with commas, right?

Yes, separators in `stroke-dasharray` should be always converted to commas, to avoid https://phabricator.wikimedia.org/T32033 .

PS: Comment: For path-data inkscape e.g uses `M 1,1 200,200`to visually split it from (1,1) to (200,200), however for path-data it is only a `pretty`-option, not related to a bug. It is usefull for people who create svgs by text-exitors. (I can't.)

**Comment by TrySound** [comment] 2021-03-04 10:21
@JoKalliauer I actually cannot reproduce this issue. See https://github.com/svg/svgo/blob/master/plugins/_path.js#L196 numbers are changed but separators are preserved. With default config I don't have a problem.

**Comment by JoKalliauer** [comment] 2021-03-04 13:40
@TrySound I think it is related to [`cleanupListOfValues`](https://github.com/svg/svgo/blob/master/plugins/cleanupListOfValues.js#L134). I will disable this feature.

## Input
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 355 355">
 <path fill="#FFF" d="M0 0h356v356H0"/>
 <g stroke="red" stroke-width="356">
  <path stroke-dasharray=".3,3.25" d="M0 178h356M178 0v356"/>
  <path stroke-dasharray="1,16.75" d="M17 178h322M178 17v322"/>
 </g>
</svg>
```
```js
'use strict'

const { extendDefaultPlugins } = require('svgo')

module.exports = {
  multipass: true,
  js2svg: {
    pretty: true,
    indent: 1
  },
  plugins: extendDefaultPlugins([
    {
      name: 'cleanupListOfValues',
      active: true
    },
  ])
}
```

## Output
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 355 355">
 <path fill="#FFF" d="M0 0h356v356H0"/>
 <g stroke="red" stroke-width="356">
  <path stroke-dasharray=".3 3.25" d="M0 178h356M178 0v356"/>
  <path stroke-dasharray="1 16.75" d="M17 178h322M178 17v322"/>
 </g>
</svg>
```

**Comment by TrySound** [comment] 2021-03-04 13:42
Got it, thanks

**Comment by KTibow** [comment] 2023-12-02 19:12
This isn't a real concern anymore, as any moderately recent `rsvg` can understand spaces. This issue should be closed by a maintainer as "not planned" as it does not need to be added.

**Comment by JoKalliauer** [comment] 2024-01-01 14:46
> This isn't a real concern anymore, as any moderately recent `rsvg` can understand spaces. This issue should be closed by a maintainer as "not planned" as it does not need to be added.

Since Wikimedia foundation (who hosts Wikipedia) updated their servers to rsvg 2.44 in May 2023 (half a year ago), this issue is not relevant any more.

**Comment by SethFalco** [comment] 2024-05-27 12:10
Indeed, I'll close this issue then if it's no longer relevant.

Thanks for the update!

**Closed by SethFalco** 2024-05-27 12:10 UTC
Labels: bug
