### ISSUE TITLE
Feature Request: Optimize embedded raster images

### ISSUE THREAD

**Issue by guiconti** [svg/svgo#1246] opened 2020-04-21 21:32 UTC
Hi! First I want to thank everyone involved in this project, it helped me a lot in the past few years.

In some of the projects that I am currently working on, we are receiving a lot of SVGs with embedded raster images. Some of these embedded images are making the SVGs bigger than what they should be. I was thinking if it makes sense to implement a plugin in SVGO that tries to improve the embedded images. Also, I would be more than happy to start working in a PR for it with some guidance.

Thanks!

**Comment by jameshfisher** [comment] 2022-07-01 10:59
Same: my SVG sizes are bloated by raster images at a resolution that is needlessly high for their size in the image.

It would be great if `svgo` reduced the resolution of raster images to match their display size in the SVG image.

(I suppose this would have to guess at a sensible DPI.)

**Comment by TPS** [comment] 2023-05-29 23:21
It might even be worth converting, e.g., an embedded PNG → lossless WebP

**Comment by TPS** [comment] 2023-05-30 11:34
This duplicates #971?

**Comment by SethFalco** [comment] 2023-09-26 23:04
Closing as a duplicate of https://github.com/svg/svgo/issues/971.

It's a nice idea, so we'll hopefully look at it soon, but I'm giving the bug reports and improvements to existing plugins priority atm.

**Closed by SethFalco** 2023-09-26 23:04 UTC
Labels: duplicate
