### ISSUE TITLE
svgo changes Id of marker but doesn't update corresponding reference in `marker-end:url(#id)`

### ISSUE THREAD

**Issue by rnwst** [svg/svgo#1719] opened 2022-12-03 02:39 UTC
**Describe the bug**
When optimizing the below SVG, svgo renames the Id of the marker from `marker` to `a`, but doesn't update the corresponding reference in `marker-end:url(#marker)`.

**To Reproduce**
1. Run svgo on the below SVG (default configuration apart from `--pretty` and `--indent=2`).
2. Observe that the resultant SVG is now missing an arrowhead when rendered.

**Expected behavior**
The reference in `marker-end:url(#marker)` must also be updated if the marker is to be renamed. Otherwise, the link is broken and the end-marker will not be displayed.

**Screenshots**
Before svgo:
![image](https://user-images.githubusercontent.com/98110034/205417976-1beb1e96-a6f3-44b6-902f-05f5bae5c520.png)
After svgo:
![image](https://user-images.githubusercontent.com/98110034/205418008-7343e135-6805-417c-ad04-b8f29f947442.png)

**Desktop (please complete the following information):**
 - SVGO Version 3.0.2
 - NodeJs Version 19.0.1
 - OS: Linux
 
**Additional context**
SVG before svgo:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="65mm" height="56mm" viewBox="0 0 65 56">
  <defs>
    <marker id="marker" markerHeight="5" markerWidth="8" orient="auto-start-reverse" style="overflow:visible">
      <path d="m0 0-2.5 2.5L6.25 0-2.5-2.5Z"/>
    </marker>
  </defs>
  <path d="M24 21v45h51" style="fill:none;stroke:#000;stroke-width:.352778;marker-start:url(#marker);marker-end:url(#marker)" transform="translate(-17 -17)"/>
</svg>
```

SVG after optimization by svgo:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="65mm" height="56mm" viewBox="0 0 65 56">
  <defs>
    <marker id="a" markerHeight="5" markerWidth="8" orient="auto-start-reverse" style="overflow:visible">
      <path d="m0 0-2.5 2.5L6.25 0-2.5-2.5Z"/>
    </marker>
  </defs>
  <path d="M24 21v45h51" style="fill:none;stroke:#000;stroke-width:.352778;marker-start:url(#a);marker-end:url(#marker)" transform="translate(-17 -17)"/>
</svg>
```

**Comment by rnwst** [comment] 2022-12-03 17:17
Some further research reveals that this bug is caused by the [cleanupIds plugin](https://github.com/svg/svgo/blob/main/plugins/cleanupIds.js).

**Comment by rnwst** [comment] 2022-12-09 19:50
For anyone coming across this issue, a temporary fix is to disable minification of Ids by the [`cleanupIds plugin`](https://github.com/svg/svgo/blob/main/plugins/cleanupIds.js), as this seems to be causing this issue:

``` javascript
const result = svgo.optimize(svgString, {
    plugins: [
      {
        name: 'preset-default',
        params: {
          overrides: {
            cleanupIds: {
              minify: false,
            },
          },
        },
      },
    ],
  });
const optimizedSVGstring = result.data;
```

**Comment by fullstackzach** [comment] 2023-05-22 20:24
Thanks! I ran into this issue too and your workaround worked for me.

**Comment by SethFalco** [comment] 2023-11-14 19:18
This looks like it's a duplicate of https://github.com/svg/svgo/issues/1725 🤔  
In any case, this has been resolved and was released in SVGO v3.0.3.

**Closed by SethFalco** 2023-11-14 19:18 UTC
Labels: bug

**Comment by rnwst** [comment] 2023-11-16 17:08
This is not a duplicate of #1725. The present issue can be avoided by disabling minification of Ids in the [`cleanupIds plugin`](https://github.com/svg/svgo/blob/main/plugins/cleanupIds.js), whereas #1725 persists even if minification of Ids is disabled.

Anyway, I can confirm that this issue no longer occurs in v3.0.3. Thanks for your work in fixing this!

**Comment by SethFalco** [comment] 2023-11-16 23:25
Ahh my bad, you're right! I didn't read through the issues properly. ^-^'

Glad it works though, feel free to report other issues if you run into any. They'll get reviewed a lot quicker next time. 👍🏽
