### ISSUE TITLE
Don't encode quotes to entities in <script> and <style>

### ISSUE THREAD

**Issue by Tyriar** [svg/svgo#176] opened 2014-01-24 19:20 UTC
By default any double quotes `"` withing a `<script>` element are converted to `&quot;`, increasing the size of the resulting file.

**Comment by icek** [comment] 2015-09-16 13:53
Same for `<style>` element and for single quote `'` which is encoded as `&apos;`

**Comment by MadLittleMods** [comment] 2015-09-17 21:05
:+1: I have the same <style> mangle:

```
<style>
	.foo {
		fill: url('#som-svg-gradient');
	}
</style>
```

**Comment by shaneparsons** [comment] 2016-03-22 18:16
+1 this is happening with quotes in a `tspan` as well.
e.g.

**input**
```
<tspan id="height">0'0"</tspan>
```

**output**
```
<tspan id="height">0&amp;apos;0&amp;quot;</tspan>
```

**Comment by jgonera** [comment] 2019-12-30 17:55
This is messing up text in my SVGs. @shaneparsons did you find a workaround?

**Comment by dphil** [comment] 2020-01-01 21:07
This was causing issues with single and double quotes in the style element of my svgs. I have not found an svgo-based solution, but a simple workaround that suffices for my case is to run a postprocessing step after svgo to find and replace the encoded quotes:
```
sed -i "s/&apos;/'/g;s/&quot;/\"/g" file.svg
```

**Comment by shaneparsons** [comment] 2020-01-06 15:38
@jgonera This was a long time ago so it's hard to remember... But I'm pretty sure I just did a find / replace after the processing. e.g.

**find:** `&amp;apos;` **replace:** `'`
**find:** `&amp;quot;` **replace:** `"`

It's not ideal... but my svgs weren't updated often so it wasn't too bad.

**Comment by XhmikosR** [comment] 2021-02-20 14:02
Confirmed this is still an issue, unfortunately :/ And it can break things as mentioned a couple of comments above.

**Comment by TrySound** [comment] 2021-09-04 17:16
Which things this break exactly? Looks like browsers interpet html entities as normal characters. Styles and scripts with `&quot;` work fine.

**Comment by TrySound** [comment] 2021-12-25 12:19
Closing until somebody provide a repro with visual regression

**Closed by TrySound** 2021-12-25 12:19 UTC
Labels: enhancement
