### ISSUE TITLE
`--multipass` moves some paths

### ISSUE THREAD

**Issue by nschloe** [svg/svgo#1857] opened 2023-11-29 13:12 UTC
Running
```
svgo --multipass in.svg
```

on

![in](https://github.com/svg/svgo/assets/181628/f2ff3137-a86e-40b4-9f65-08f97dcb9cd2)

gives

![in-opti-multipass](https://github.com/svg/svgo/assets/181628/d9b681de-d392-4e31-bc8f-ec93fdac7191)

Note how some of the paths are moved.

This is with svgo 3.0.4.

**Comment by SethFalco** [comment] 2023-11-29 22:27
Hey! Thanks for reporting the issue.

This is ultimately a duplicate of https://github.com/svg/svgo/issues/1855.
Sorry for the headache, it was a regression introduced in the last release! This has already been resolved in `main` and will be released this evening in SVGO v3.0.5.

**Closed by SethFalco** 2023-11-29 22:27 UTC
Labels: bug
