### ISSUE TITLE
--datauri 'unenc' add 'data:image/svg+xml,data:image/svg+xml,'

### ISSUE THREAD

**Issue by FrancoJavierGadea** [svg/svgo#2048] opened 2024-07-04 19:43 UTC
**Describe the bug**

`--datauri 'unenc'` add to ouput SVG `"data:image/svg+xml,data:image/svg+xml,"`

- SVGO Version: 3.3.2
- NodeJs Version: 18, 22
- OS: Windows

[reproduce on stackblitz](https://stackblitz.com/edit/stackblitz-starters-enayzf?file=package.json)

**Comment by SethFalco** [comment] 2024-09-07 21:05
Hey! Thanks for reporting the issue. This has already been reported so I'll close as as a duplicate of https://github.com/svg/svgo/issues/997.

**Closed by SethFalco** 2024-09-07 21:05 UTC
