### ISSUE TITLE
Self closing tags for non void elements 

### ISSUE THREAD

**Issue by bradbarrow** [svg/svgo#397] opened 2015-07-06 12:29 UTC
### Void Elements

See [W3 HTML Syntax - Elements](http://www.w3.org/TR/html-markup/syntax.html#syntax-elements)

There's a shortlist of elements in HTML5 that are considered void elements. Void elements do not need a closing tag and are instead terminated with `/>`.

For e.g. `<hr />`

### svgo (js2svg) short tags

[Here](https://github.com/svg/svgo/blob/master/lib/svgo/js2svg.js#L236) you implement the closing `/>` for any element that has no content (empty elements and short tags). I assume this is an optimisation strategy.

### SVG in HTML

When the SVG resulting from svgo is put into an HTML document and served into a browser, many browsers will autocorrect the markup. They will find tags that are not permitted to use `/>`, and will automatically insert a closing tag. 

E.g. `<path d="M4 14l20 20 20-20"/>` becomes `<path d="M4 14l20 20 20-20"><path>` when loaded in an HTML page in Google Chrome.

### Issue

Aside from the fact that it's technically valid (since it's SVG not HTML), 

> A non-void element must have an end tag, unless the subsection for that element in the HTML elements section of this reference indicates that its end tag can be omitted.

this has caused me issue in an isomorphic ReactJS application. The server responds with markup including the `/>`, which Chrome replaces with `</path>`. Then, the ReactJS client side application attempts to reuse markup but finds an incosistency between the new markup to be injected (which again contains the `/>` and the markup already in the DOM `</path>`. ReactJS therefore throws a warning.

### Solution (PR)

I've implemented a simple config option to be forwarded to js2svg to decide between using short or full closing tags:

https://github.com/svg/svgo/pull/396

**Comment by GreLI** [comment] 2016-01-04 17:16
I guess the issue is obsolete since the PR is merged.

**Closed by GreLI** 2016-01-04 17:16 UTC
