### ISSUE TITLE
Illustrator error

### ISSUE THREAD

**Issue by kirkstrobeck** [svg/svgo#314] opened 2015-02-09 18:51 UTC
I get the following error:

    Invalid character entity

When my Illustrator save has the following options:

![screen shot 2015-02-09 at 10 48 50 am](https://cloud.githubusercontent.com/assets/241963/6113045/3eb3e624-b049-11e4-8e61-827f670f1bd4.png)

I want to retain the Illustrator editing capabilities, but it seems to be the setting causing errors. I am happy to pass the file thru any gulp filter prior to using `gulp-svgmin`, but none seem to work. I’ve tried `gulp-svg-sprite` and `gulp-svgstore` prior to `gulp-svgmin` to no avail.

**Comment by GreLI** [comment] 2015-02-09 19:59
Probably, it's duplicate of #272.

**Comment by GreLI** [comment] 2015-03-22 18:01
Yes, it is. I can only suggest you to turn off «Preserve Illustrator Editing Capabilities» and don't include XMP — they are useless anyway, since svgo wipe them out anyway.

**Closed** 2016-01-04 17:22 UTC
Labels: duplicate
