### ISSUE TITLE
Enabling both `cleanupIDs` and `prefixIds` does not work as expected

### ISSUE THREAD

**Issue by dannobytes** [svg/svgo#1406] opened 2021-03-05 00:48 UTC
**Describe the bug**
When attempting to optimize with both `cleanupIDs` and `prefixIds` plugins enabled, I expect the IDs to be minified AND prefixed with the SVG filename. However, it instead only prefixes the IDs with the filename if `cleanupIDs.minify` is disabled.

There are valid reasons why minifying the ID and then prefixing it with the filename are necessary, mainly when inlining multiple SVGs on the same page. Without unique prefixes, duplicate IDs will conflict with one another.

**To Reproduce**
1. Enable both plugins
```js
// svgo.config.js
const { extendDefaultPlugins } = require('svgo')

module.exports = {
  multipass: true,
  plugins: extendDefaultPlugins([
    'cleanupIDs',
    'prefixIds'
  ])
}
```
2. Run the optimizer on an SVG that contains IDs. Here's a sample SVG:
```html
<!-- my-file.svg -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46 46">
  <g clip-path="url(#test-aaa)">
    <path d="M37.375 42.167H4.792a.958.958 0 0 1-.959-.959V8.626a1.917 1.917 0 1 0-3.833 0v33.542A3.833 3.833 0 0 0 3.833 46h33.542a1.917 1.917 0 0 0 0-3.833z" fill="#99D099"/>
    <rect fill="#008A00" height="39.531" rx="3" width="39.531" x="6.469"/>
    <g clip-path="url(#test-bbb)">
      <path d="M23.15 27.192a1.168 1.168 0 0 0 1.168 1.168h3.114a1.168 1.168 0 0 0 1.168-1.168v-4.866a.195.195 0 0 1 .195-.195h4.866a1.168 1.168 0 0 0 1.169-1.168V17.85a1.168 1.168 0 0 0-1.169-1.168h-4.866a.195.195 0 0 1-.195-.195V11.62a1.168 1.168 0 0 0-1.168-1.168h-3.114a1.168 1.168 0 0 0-1.168 1.168v4.866a.195.195 0 0 1-.195.195H18.09a1.168 1.168 0 0 0-1.168 1.168v3.114a1.168 1.168 0 0 0 1.168 1.168h4.866a.195.195 0 0 1 .195.195v4.866z" fill="#CCE7CC"/>
    </g>
  </g>
  <defs>
    <clipPath id="test-aaa">
      <path d="M0 0h46v46H0z" fill="#fff"/>
    </clipPath>
    <clipPath id="test-bbb">
      <path d="M16.531 10.063h18.688v18.688H16.531z" fill="#fff"/>
    </clipPath>
  </defs>
</svg>
```

3. Run the optimizer
4. See SVG. Ids were minified but not prefixed.

**Expected behavior**
Expected SVG should be as follows
```html
<!-- my-file.svg -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46 46">
  <g clip-path="url(#my-file_svg__a)">
    <path d="M37.375 42.167H4.792a.958.958 0 0 1-.959-.959V8.626a1.917 1.917 0 1 0-3.833 0v33.542A3.833 3.833 0 0 0 3.833 46h33.542a1.917 1.917 0 0 0 0-3.833z" fill="#99D099"/>
    <rect fill="#008A00" height="39.531" rx="3" width="39.531" x="6.469"/>
    <g clip-path="url(#my-file_svg__b)">
      <path d="M23.15 27.192a1.168 1.168 0 0 0 1.168 1.168h3.114a1.168 1.168 0 0 0 1.168-1.168v-4.866a.195.195 0 0 1 .195-.195h4.866a1.168 1.168 0 0 0 1.169-1.168V17.85a1.168 1.168 0 0 0-1.169-1.168h-4.866a.195.195 0 0 1-.195-.195V11.62a1.168 1.168 0 0 0-1.168-1.168h-3.114a1.168 1.168 0 0 0-1.168 1.168v4.866a.195.195 0 0 1-.195.195H18.09a1.168 1.168 0 0 0-1.168 1.168v3.114a1.168 1.168 0 0 0 1.168 1.168h4.866a.195.195 0 0 1 .195.195v4.866z" fill="#CCE7CC"/>
    </g>
  </g>
  <defs>
    <clipPath id="my-file_svg__a">
      <path d="M0 0h46v46H0z" fill="#fff"/>
    </clipPath>
    <clipPath id="my-file_svg__b">
      <path d="M16.531 10.063h18.688v18.688H16.531z" fill="#fff"/>
    </clipPath>
  </defs>
</svg>
```

**Desktop (please complete the following information):**
 - SVGO Version 2.2.0
 - NodeJs Version 12.18.0
 - OS: OSX

**Comment by polarathene** [comment] 2021-04-16 11:24
> Without unique prefixes, duplicate IDs will conflict with one another.

<details>
<summary>My misunderstanding of needing unique ID</summary>

Just curious but aren't you able to produce a unique ID, class or depending on context a selector that relies on more than just the svg element for querying (eg `div.example > svg {}`), IIRC JS can use a selector for finding a element match as well.

Last I knew, relying on IDs was generally frowned upon vs classes, be that for styling or targeting an element with JS.

In some cases where users ask for this, I imagine you would still have the scenario of using the same SVG graphic multiple times but also wanting to isolate them for using JS or CSS to produce variations or different behaviour logic. I'm curious how that's resolved other than giving the `<svg>` root element a unique class (or ID) and using a selector as you would?

~~The SVG itself shouldn't be referencing any content outside of it, so is it rather a developer usage concern?~~ (**EDIT:** It does :confused: ) Or have I misunderstood something here?

eg instead of `#my-file_svg__a`, you could use `#my-file_svg #a`

If you're going to use a selector to modify the SVG via JS or styles via CSS, might as well use a better selector. I get that's not always an option though if you're distributing a large library of SVG files for third-parties and you want to minimize the upfront effort for those users.

---

</details>

**EDIT:** Technically this works on SVGO v1, just not with your example which has a bug.

In v2.1 static plugin processing order was added and appears to have accidentally mixed the order up (v2 also changed plugin order but I'm not sure if was an issue back then too):

https://github.com/svg/svgo/blob/3d79f57a10d7b3dba4bcd30d0b94e22410626cae/lib/svgo/config.js#L5-L18

<details>

<summary>More info (original message while looking into the issue)</summary>

---

## Earlier Notes

While I was able to reproduce this, it turned out to be with SVGO v1.x via SVGR. I identified the bug which was specific to `id` in `<defs>` being ignored and thus the problem. [That was already resolved though](https://github.com/svg/svgo/commit/77464801e7f38a62ca4542033c8099d38b90d5f0) and part of the new v2.0 release I think, it didn't seem to get backported to SVG 1.x, and that seems to be due to the project not having separate major version branches, so all v2 work would have been in the same branch or something building up to a v2 release? Unfortunate :man_shrugging: 

The `cleanupIDs` plugin has a basic "minifier" that doesn't generate a value based on content it's replacing, so you'd not have noticed any difference with `prefixIds` plugin enabled vs disabled. What happens is as shown with it's list order on the README, your IDs are prefixed first, then `cleanupIDs` plugin runs... while you expected the order to be the other way around, which would make the most sense...? (**EDIT:** It appears this is how it originally was in v1)

I'm not sure why the current processing order is like that. I noticed that with the mentioned v1.x bug fix that only made it to v2 did work as you'd expect with `prefixIds` running after `cleanupIDs`. v2 changed how plugins are loaded, and then in v2.1 (mid feb) [introduced a static order](https://github.com/svg/svgo/commit/2965e8ccdb84a9a17353bf6c41fe83da7e9f57ba#diff-5f68f85e9d895302c78eaa66a60bb4557984ea4e877523c68fccc19c38b05c18), which introduced the static default order. 

**`cleanupIDs` running before `prefixIds` was likely an accident**.

</details>

--

## Workarounds

Note that you can specify a prefix in `cleanupIDs` plugin params:

https://github.com/svg/svgo/blob/3d79f57a10d7b3dba4bcd30d0b94e22410626cae/plugins/cleanupIDs.js#L12-L19

How useful that is to you depends on how you want to run SVGO, if using something like webpack you can pass the filename context in to adjust the config param for each asset processed. It only accepts a string, not a function like `prefixIds` plugin. The minifier ID generator is also not configurable :disappointed: 

Alternatively  in the meantime you should be able to do two passes using slightly different config each: `cleanupIDs` first. then `prefixIds`?

---

## Sidenote - Optimizing prefix size

In looking into this, I'm now better aware of the need for the unique ID regarding internal usage with defs. I had two instances of this MDN gradient example and noticed changing ones gradient colours affected the other when they're both used as separate inline SVG elements in an HTML document.

When you're only interested in avoiding internal conflicts like that, rather than targeting those IDs via selectors for adjustments at runtime, you could potentially have shorter prefixes via a hash on the filename instead, `styled-components` and others use this for minification:

**`svgo.config.js`:**

```js
// DJB2a (XOR variant) is a simple hashing function, reduces input to 32-bits
// Same hashing algorithm as used by `styled-components`.
const SEED = 5381
function djb2a(str) {
  let hash = SEED

  for (let i = 0; i < str.length; i++) {
    hash = (hash * 33) ^ str.charCodeAt(i)
  }

  // Cast to 32-bit uint
  return hash >>> 0
}

// Converts string input to a 32-bit base36 string (0-9, a-z)
// '_' prefix to prevent invalid first chars for CSS class names
const getShortKey = (node, extra) => `_` + djb2a(extra.path).toString(36)

module.exports = {
  datauri: 'unenc',
  js2svg: {
    indent: 2,
    pretty: true,
  },
  plugins: [{
    name: 'prefixIds',
    params: {
      prefix: getShortKey
    }
  }]
}
```

Would be more optimal as a suffix (you'd still want a delimiter between the minified class/id though).

Using it as a generator function for `cleanupIDs` instead to further reduce file size by removing the need for a prefix/suffix may sound good but would also be more fragile as this hashing algorithm is a simple one and only covers a range up to 32-bits (a collision after 16-bits aka 65,536 hashes is roughly 50% likely, but with this hash function quite possibly earlier)

**Comment by TrySound** [comment] 2021-09-13 14:46
Should be fixed in https://github.com/svg/svgo/releases/tag/v2.6.0

**Closed by TrySound** 2021-09-13 14:46 UTC
Labels: bug
