### ISSUE TITLE
[BUG] Optimized SVG is different than source Ajofrín.svg

### ISSUE THREAD

**Issue by sk-** [svg/svgo#1384] opened 2021-02-27 16:26 UTC
Using the (wip) integration test tool we identified an issue while optimizing the file `Ajofrín.svg` with the default settings.

## SVGO version
2.1.0

## Differences
The resulting image has a much thicker crown

## Sources
Original:

[source.svg.txt](https://github.com/svg/svgo/files/6054916/source.svg.txt)

Optimized:

[optimized.svg.txt](https://github.com/svg/svgo/files/6054915/optimized.svg.txt)

## Renders
Here are the two rendered images for comparison:

Original:

![source](https://user-images.githubusercontent.com/911768/109393207-2785b600-78ff-11eb-8278-a33a5bebd71b.png)

Optimized:

![optimized](https://user-images.githubusercontent.com/911768/109393203-248ac580-78ff-11eb-9e77-545b66a34190.png)

Diff:

![diff](https://user-images.githubusercontent.com/911768/109393254-5ef46280-78ff-11eb-8612-c532fbaa63d4.png)

**Comment by TrySound** [comment] 2021-02-27 20:46
Duplicate of https://github.com/svg/svgo/issues/1385

**Closed by TrySound** 2021-02-27 20:46 UTC
Labels: bug
