### ISSUE TITLE
collapseGroups loses style

### ISSUE THREAD

**Issue by charlag** [svg/svgo#1453] opened 2021-03-24 11:12 UTC
**Describe the bug**
When collapseGroups is enabled (default) style block might be lost.

**To Reproduce**
Say we have SVG like this:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
        xmlns="http://www.w3.org/2000/svg"
        xml:space="preserve"
        preserveAspectRatio="xMinYMid"
        enable-background="new 0 0 1280 800"
        viewBox="0 0 1054.473 236.49001"
        y="0px"
        x="0px"
        id="Ebene_1"
        version="1.1">
    <defs
     id="defs25" />
    <g id="g33"
     style="fill:#840010"
     transform="translate(-132.62802,-222.799)">
      <path
         d="m 155.503,222.799 c -12.64,0 -22.875,10.246 -22.875,22.872 v 211.23 c 0,0.801 0.046,1.608 0.123,2.388 8.5,-3.167 17.524,-6.629 27.054,-10.436 66.336,-26.48 120.569,-48.994 120.618,-74.415 0,-0.814 -0.056,-1.636 -0.172,-2.458 -3.43,-25.098 -63.407,-32.879 -63.324,-44.381 0.007,-0.611 0.18,-1.25 0.548,-1.889 7.205,-12.619 35.743,-12.015 46.253,-12.907 10.519,-0.913 35.206,-0.724 36.399,-8.244 0.035,-0.232 0.057,-0.463 0.057,-0.695 0.028,-6.987 -16.977,-9.726 -16.977,-9.726 0,0 20.635,3.083 20.579,11.11 0,0.393 -0.048,0.8 -0.158,1.214 -2.222,8.624 -20.379,10.246 -32.386,10.835 -11.356,0.569 -28.648,1.861 -28.707,7.408 -0.007,0.323 0.049,0.66 0.165,1.004 2.71,8.11 66.09,12.015 106.64,33.061 23.335,12.099 34.94,32.422 40.263,53.418 v -166.52 c 0,-12.626 -10.243,-22.872 -22.869,-22.872 H 155.503 z"
         id="a" />
    </g>
</svg>
```

group has a fill style.

After calling:
```js
const optimizedSvg = optimize(sanitizedSvg, {
	plugins: extendDefaultPlugins([
		{
			name: 'removeViewBox',
			active: false,
		},
		{
			name: 'removeScriptElement',
			active: true,
		},
	])
})

```

we get this:

```svg
<svg viewBox="0 0 1054.473 236.49" preserveAspectRatio="xMinYMid" xml:space="preserve" xmlns="http://www.w3.org/2000/svg"><path d="M22.875 0C10.235 0 0 10.246 0 22.872v211.23c0 .801.046 1.608.123 2.388 8.5-3.167 17.524-6.629 27.054-10.436 66.336-26.48 120.569-48.994 120.618-74.415 0-.814-.056-1.636-.172-2.458-3.43-25.098-63.407-32.879-63.324-44.381.007-.611.18-1.25.548-1.889 7.205-12.619 35.743-12.015 46.253-12.907 10.519-.913 35.206-.724 36.399-8.244.035-.232.057-.463.057-.695.028-6.987-16.977-9.726-16.977-9.726s20.635 3.083 20.579 11.11c0 .393-.048.8-.158 1.214-2.222 8.624-20.379 10.246-32.386 10.835-11.356.569-28.648 1.861-28.707 7.408-.007.323.049.66.165 1.004 2.71 8.11 66.09 12.015 106.64 33.061 23.335 12.099 34.94 32.422 40.263 53.418V22.869c0-12.626-10.243-22.872-22.869-22.872H22.875z"/></svg>
```
(fill is lost).

When collapseGroups is disabled this does not happen because group is kept.

**Expected behavior**
Group with style definition is not considered useless

**Desktop (please complete the following information):**
 - SVGO Version 2.2.2
 - NodeJs Version 14.15.4
 - OS: Linux

**Comment by TrySound** [comment] 2021-03-24 13:19
Hi @charlag. I cannot reproduce this issue. Group attributes are inherited by children and group remove. Here's what I get
```
<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" preserveAspectRatio="xMinYMid" viewBox="0 0 1054.473 236.49"><path d="M155.503 222.799c-12.64 0-22.875 10.246-22.875 22.872v211.23c0 .801.046 1.608.123 2.388 8.5-3.167 17.524-6.629 27.054-10.436 66.336-26.48 120.569-48.994 120.618-74.415 0-.814-.056-1.636-.172-2.458-3.43-25.098-63.407-32.879-63.324-44.381.007-.611.18-1.25.548-1.889 7.205-12.619 35.743-12.015 46.253-12.907 10.519-.913 35.206-.724 36.399-8.244.035-.232.057-.463.057-.695.028-6.987-16.977-9.726-16.977-9.726s20.635 3.083 20.579 11.11c0 .393-.048.8-.158 1.214-2.222 8.624-20.379 10.246-32.386 10.835-11.356.569-28.648 1.861-28.707 7.408-.007.323.049.66.165 1.004 2.71 8.11 66.09 12.015 106.64 33.061 23.335 12.099 34.94 32.422 40.263 53.418v-166.52c0-12.626-10.243-22.872-22.869-22.872H155.503z" transform="translate(-132.628 -222.799)" style="fill:#840010"/></svg>
```

**Comment by charlag** [comment] 2021-03-24 14:01
That's so odd.

program:

```js
import {optimize, extendDefaultPlugins} from "svgo"

const svg = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
        xmlns="http://www.w3.org/2000/svg"
        xml:space="preserve"
        preserveAspectRatio="xMinYMid"
        enable-background="new 0 0 1280 800"
        viewBox="0 0 1054.473 236.49001"
        y="0px"
        x="0px"
        id="Ebene_1"
        version="1.1">
    <defs
     id="defs25" />
    <g id="g33"
     style="fill:#840010"
     transform="translate(-132.62802,-222.799)">
      <path
         d="m 155.503,222.799 c -12.64,0 -22.875,10.246 -22.875,22.872 v 211.23 c 0,0.801 0.046,1.608 0.123,2.388 8.5,-3.167 17.524,-6.629 27.054,-10.436 66.336,-26.48 120.569,-48.994 120.618,-74.415 0,-0.814 -0.056,-1.636 -0.172,-2.458 -3.43,-25.098 -63.407,-32.879 -63.324,-44.381 0.007,-0.611 0.18,-1.25 0.548,-1.889 7.205,-12.619 35.743,-12.015 46.253,-12.907 10.519,-0.913 35.206,-0.724 36.399,-8.244 0.035,-0.232 0.057,-0.463 0.057,-0.695 0.028,-6.987 -16.977,-9.726 -16.977,-9.726 0,0 20.635,3.083 20.579,11.11 0,0.393 -0.048,0.8 -0.158,1.214 -2.222,8.624 -20.379,10.246 -32.386,10.835 -11.356,0.569 -28.648,1.861 -28.707,7.408 -0.007,0.323 0.049,0.66 0.165,1.004 2.71,8.11 66.09,12.015 106.64,33.061 23.335,12.099 34.94,32.422 40.263,53.418 v -166.52 c 0,-12.626 -10.243,-22.872 -22.869,-22.872 H 155.503 z"
         id="a" />
    </g>
</svg>`


const optimized = optimize(svg)

console.log(optimized)
```
```
➜  node test-svgo.js 
{
  data: '<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" preserveAspectRatio="xMinYMid" viewBox="0 0 1054.473 236.49"><path d="M22.875 0C10.235 0 0 10.246 0 22.872v211.23c0 .801.046 1.608.123 2.388 8.5-3.167 17.524-6.629 27.054-10.436 66.336-26.48 120.569-48.994 120.618-74.415 0-.814-.056-1.636-.172-2.458-3.43-25.098-63.407-32.879-63.324-44.381.007-.611.18-1.25.548-1.889 7.205-12.619 35.743-12.015 46.253-12.907 10.519-.913 35.206-.724 36.399-8.244.035-.232.057-.463.057-.695.028-6.987-16.977-9.726-16.977-9.726s20.635 3.083 20.579 11.11c0 .393-.048.8-.158 1.214-2.222 8.624-20.379 10.246-32.386 10.835-11.356.569-28.648 1.861-28.707 7.408-.007.323.049.66.165 1.004 2.71 8.11 66.09 12.015 106.64 33.061 23.335 12.099 34.94 32.422 40.263 53.418V22.869c0-12.626-10.243-22.872-22.869-22.872H22.875z"/></svg>',
  info: { width: undefined, height: undefined }
}
```

840010 is nowhere to be found...

**Comment by TrySound** [comment] 2021-03-24 14:52
Got it. Looks like this is fixed in master. Will release soon.

**Comment by charlag** [comment] 2021-03-24 14:52
Ah, glad to hear that, thanks for checking it!

**Comment by TrySound** [comment] 2021-03-28 11:01
Fixed in https://github.com/svg/svgo/releases/tag/v2.3.0

**Closed by TrySound** 2021-03-28 11:01 UTC
Labels: bug, solved in master
