### ISSUE TITLE
CLI option to disable plugins is no longer available

### ISSUE THREAD

**Issue by leonid-chernyavskiy** [svg/svgo#1622] opened 2021-11-17 10:15 UTC
**Describe the bug**
CLI option to disable plugins is no longer available. It makes at least one (hah, probably many) developer sad.

**To Reproduce**
1. Go to console
2. Type svgo --disable=removeViewBox some.svg
3. Press enter
4. See error - unknown option

**Expected behavior**
Simple working option to remove some plugin by choice. And not removing functionality with an update.

**Screenshots**
svgo --disable=removeViewBox draft.svg
error: unknown option '--disable=removeViewBox'

**Desktop (please complete the following information):**
 - SVGO Version [2.8.0]
 - NodeJs Version [12.22.7]
 - OS: [windows 10]
 
**Additional context**
So sad.

**Comment by TrySound** [comment] 2021-11-17 10:26
It was removed in major release. So not a bug.
https://github.com/svg/svgo/releases/tag/v2.0.0

I consider adding it back at some point but it should be able to work with presets somehow. This is still need to be figured out.

**Comment by SethFalco** [comment] 2024-06-14 12:35
Closing as a duplicate of https://github.com/svg/svgo/issues/1356 which has more context/information.

**Closed by SethFalco** 2024-06-14 12:35 UTC
Labels: enhancement
