### ISSUE TITLE
Removes a fill/color when it probably shouldn't

### ISSUE THREAD

**Issue by raine** [svg/svgo#769] opened 2017-07-17 13:10 UTC
[svgs.zip](https://github.com/svg/svgo/files/1152668/svgs.zip)

Above zip has a version of the svg before running it through `svgo`, and one after.

The red color was changed to the original svg with Inkscape. Running `svgo` removes the change.

**Comment by GreLI** [comment] 2017-07-18 18:58
That's because of CSS styles. SVGO doesn't handle them.

**Comment by strarsis** [comment] 2017-10-23 12:38
With https://github.com/svg/svgo/pull/592 merged in, native CSS support is added - 
how can it be used to fix this issue? Is this caused by a specific plugin?

**Comment by GreLI** [comment] 2017-10-23 17:24
Yep, it helps.

**Comment by XhmikosR** [comment] 2021-02-25 08:38
@TrySound maybe this is also fixed in 2.1.0? The result svg looks the same to me with the default options.

**Comment by TrySound** [comment] 2021-02-25 10:57
Fixed

**Closed by TrySound** 2021-02-25 10:57 UTC
