### ISSUE TITLE
Map IDs to Classes

### ISSUE THREAD

**Issue by infn8** [svg/svgo#494] opened 2016-02-08 18:37 UTC
is it possible to add a plugin that would remove the id attr from an element and map it to a class with an optional prefix and / or postfix?
#### For example

```
- mapIDsToClasses:
    prefix: 'svg-'
    postfix: ''
```

would map:

```
<path id="arrow" d="M50 514.26l-25 25 25 25z"/>
```

to:

```
<path class="svg-arrow" d="M50 514.26l-25 25 25 25z"/>
```
#### Additionally:

This:

```
<rect id="cool-rect" class="cool-things" x="13" fill="#FFFFFF" width="4" height="30"/>
```

would map to:

```
<rect class="cool-things svg-cool-rect" x="13" fill="#FFFFFF" width="4" height="30"/>
```

My reason is that Group and path names in Adobe Illustrator come out as IDs when you save as an SVG but if you insert the resulting SVG into an HTML doc more than once it will invalidate the document because it will have more than one element with the same ID 

Thoughts?

**Comment by GreLI** [comment] 2016-02-09 13:58
Well, it's totally possilble. Couple of caveats though:

1. `cleanupIDs` will remove unused IDs. So, the plugin should run before it, or `cleanupIDs` needs to be disabled, if these IDs aren't being referenced. If they are, references should also be updated of course.
2. SVGO cannot parse CSS for now. So, replacing IDs there requires some additional managing.

May be it's better just to update `cleanupIDs` to work in a such manner through option.

**Comment by infn8** [comment] 2016-02-09 15:30
It would for sure need to run before ```cleanupIDs``` but after it does run ```cleanupIDs``` would have no IDs to cleanup.  

Re: CSS, I was thinking a little more brute force in that each element would only care about itself.
```
class="
{any pre existing value of class attribute}
{optional space if class attribute was not already empty}
{prefix}
{value of id attribute}
{postfix}
"
``` 
Then remove id attribute and that's it.  No need to parse CSS.  But if we can add elegance or intelligently extend another function that would be boss.  Adding it as a param to ```cleanupIDs``` would ensure it ran first!  

Thoughts?

**Comment by GreLI** [comment] 2016-02-09 18:38
No doubts about `class` content. I was talking about selectors in possible `<style>` declarations that can use IDs.

**Comment by infn8** [comment] 2016-02-09 19:34
Great point!  I had not thought of that.  It could just be a documented shortfall of that option.  Are there any other features you're considering that might need, or benefit from, CSS parsing?  

This doesn't seem like the cost benefit is there with this one feature on its own.

**Comment by GreLI** [comment] 2016-02-09 21:00
Yeah, CSS parsing is desirable feature. At least for checking styles. It's important to know in some places whether there is `fill` or `stroke` property for example. [There is already a method](https://github.com/svg/svgo/blob/master/lib/svgo/jsAPI.js) `computedAttr` but it checks only for (perhaps inherited) attributes for now.

Of course, there could be some optimizations. E.g. remove useless styles, move styles used only once to corresponding element (it should be shorter usually) — there is already PR #454, or if there a bunch of repeated styles assign it to a class.

Unfortunately, it requires some work which I have no time for. Parse CSS, construct AST, bind with DOM, etc…

**Comment by dangayle** [comment] 2017-02-02 21:36
If you remove IDs, how do you use a `<use xlink:href="#arrow-right" />` type of reference?

**Comment by infn8** [comment] 2017-02-04 03:41
@dangayle I don't think you could but the reason i want to strip ids is because i plan on using the same svg in the dom in several places and best practices say that your ids should all be unique. You would have to decide whether or not you would need to use references like that before stripping the ids.

**Comment by strarsis** [comment] 2017-04-05 17:47
Inlining may be an option, inlineStyles plugin PR: https://github.com/svg/svgo/pull/592
Prefix plugin PR: https://github.com/svg/svgo/pull/700

**Comment by peteruithoven** [comment] 2020-07-07 09:49
( Figma can also add the layer names as id's, but it does make sure that they are unique automatically. So if two items in Figma are named "Shape" they will get the ids "Shape" and "Shape_2". So in the case of figma there is less need for this. )

**Closed** 2021-10-02 11:50 UTC
Labels: enhancement

**Comment by chrisjshull** [comment] 2021-10-02 20:50
@TrySound - this request still seems valid and very useful. Can you discuss why it was closed?

**Comment by TrySound** [comment] 2021-10-03 10:31
@chrisjshull Mapping ids to classes is not safe as there can be references to ids in links. prefixIds plugin should do the trick, maybe with some template prefix. Depends on exact usage.

**Comment by chrisjshull** [comment] 2021-10-04 02:56
if I use the same SVG multiple times, e.g. by inserting the SVG via JS via a template, how will prefixIds help? Won't I end up with the same (now prefixed) ID multiple times on my page?

I'm also happy to have svgo throw an error if it sees references to ids in links (if I had a id-to-class setting enabled). 

Can we please reopen this?

**Comment by TrySound** [comment] 2021-10-04 11:08
You can specify template in prefix and generate unique_id per usage.
```
{
  name: 'prefixIds',
  params: {
    prefix: "{{unique_id}}__"
  }
}
```

If you want a linter to fail on ids write custom plugin.
```js
const plugin = {
  type: 'visitor',
  name: 'lint-ids',
  fn: () => {
    return {
      element: {
        enter: node => {
          if (node.attributes['xlink:href'] != null) {
            throw Error(`Found unexpected reference: "${node.attributes['xlink:href']}"`)
          }
        }
      }
    }
  }
}
```

The issue is out of svgo scope. But you can use SVGO to build more tools for your needs.

**Comment by chrisjshull** [comment] 2021-10-04 11:13
> You can specify template in prefix and generate unique_id per usage.

Are you suggesting I bundle svgo into the JS I send to each end-user's browser just so that I can set a unique prefix each time I insert the same SVG into the DOM?

**Comment by TrySound** [comment] 2021-10-04 11:18
SVGO only inject template syntax. You can use this template with framework or template engine you use to build your app.

**Comment by chrisjshull** [comment] 2021-10-04 11:22
Oh, I see - you mean literally have `{{unique_id}}__` and then in runtime JS swap out `{{unique_id}}` with a random identifier on each insert. That's a tad expensive as you can't clone nodes after the first DOM parse (first need to string manipulation), but I guess one could manage. Ty!
