### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by vdecree** [svg/svgo#432] opened 2015-09-24 20:10 UTC
Hi there,

Hopefully this is the right place to post this. I'm getting an error that I've never had before and randomly mid-way through a project:

```
C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\lib\svgo\plugins.js
:46
        items.content = items.content.filter(function(item) {
                                     ^
TypeError: Cannot read property 'filter' of undefined
    at monkeys (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\lib
\svgo\plugins.js:46:38)
    at perItem (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\lib
\svgo\plugins.js:77:12)
    at C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\lib\svgo\plu
gins.js:18:24
    at Array.forEach (native)
    at module.exports (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\s
vgo\lib\svgo\plugins.js:14:13)
    at C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\lib\svgo.js:
63:17
    at Object.sax.onend (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules
\svgo\lib\svgo\svg2js.js:140:26)
    at emit (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\node_m
odules\sax\lib\sax.js:625:33)
    at end (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\node_mo
dules\sax\lib\sax.js:667:3)
    at Object.write (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svg
o\node_modules\sax\lib\sax.js:929:30)
```

I've not changed anything or update any files. Can anyone point me in the right direction?

**Comment by GreLI** [comment] 2015-09-25 17:48
That's odd. Content of any element should be an array, so no such an error should appear. It's hard to say anything without config and files. Probably there is some bad plugin. May be you're using old node.js or svgo version.

**Comment by GreLI** [comment] 2015-11-21 11:29
Does it reproduce with latest svgo version. If so, can you provide a sample file?

**Comment by arnogues** [comment] 2016-01-05 07:40
For information the problem comes when one of the SVG files is corrupted

**Comment by GreLI** [comment] 2016-02-28 20:44
It's hard to say without further info, but it probably have been fixed by #435 or other error handling measures.

**Closed by GreLI** 2016-02-28 20:44 UTC

**Comment by arthurzakharov** [comment] 2018-08-26 12:25
I have the same problem. The point is that one of your svg files is corrupted(broken). In my case two svg files were simply empty. Advise to look through all svg files, specially recently added and check. If nothing special, look into git history and delete one by one svg files

**Comment by gwagroves** [comment] 2019-08-07 10:31
Got this error because of a typo in a command line option name:

```
svgo *.svg --disable=removeViewBox --enabled=removeDimensions
```

`--enabled` should be `--enable`
