### ISSUE TITLE
Fails to convert font with id containing "." character

### ISSUE THREAD

**Issue by waageher** [svg/svgo#768] opened 2017-07-14 06:20 UTC
If the SVG contains font with id value with "." character for example:
`<font id="ROMANS.SHX" ><font-face font-family="ROMANS.SHX.shx" /> ....`
it fails to process it and reports no error (just crash).

**Comment by SethFalco** [comment] 2023-11-16 12:44
Hey, and thanks for reporting the issue!

I'm unable to reproduce this behavior using the following SVG and config:

**`original.svg`**
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24">
  <font id="ROMANS.SHX" >
    <font-face font-family="ROMANS.SHX.shx" />
  </font>
</svg>
```

**`svgo.config.js`**
```svg
module.exports = {
  js2svg: {
    pretty: true,
    indent: 2,
  },
  plugins: [
    "preset-default",
  ],
};
```

Given the time that has passed, it's likely that the issue has already been resolved in the latest release. Feel free to open another issue if you can still reproduce this in a more recent version, though!

**Closed by SethFalco** 2023-11-16 12:44 UTC
Labels: cannot reproduce
